---
agnosticv_operator_namespace: agnosticv-operator
agnosticv_version: v0.0.8
anarchy_operator_app_domain: apps.cluster-babylon-crc.babylon-crc.gpte.rht-labs.com
anarchy_operator_namespace: anarchy-operator
anarchy_version: 0.1.8
babylon_tower_url: https://tower.t01.gpte.rht-labs.com
babylon_tower_creds_secret: babylon1-api-creds
babylon_tower_job_path: /api/v2/job_templates/job-runner/launch/
poolboy_namespace: poolboy
poolboy_version: 0.1.7

operators:
  deploy:
    agnosticv:
      AGNOSTICV_IMAGE: quay.io/gpte-devops-automation/agnosticv-operator:{{ agnosticv_version }}
      NAMESPACE: "{{ agnosticv_operator_namespace }}"
    anarchy:
      ANARCHY_IMAGE: quay.io/gpte-devops-automation/anarchy-operator:{{ anarchy_version }}
      ANSIBLE_RUNNER_IMAGE: quay.io/gpte-devops-automation/anarchy-ansible-runner:{{ anarchy_version }}
      APP_DOMAIN: "{{ anarchy_operator_app_domain }}"
      NAMESPACE: "{{ anarchy_operator_namespace }}"
    anarchy_api:
      TOWER_URL: "{{ tower_url }}"
      TOWER_USER: "{{ tower_user }}"
      TOWER_PASSWORD: "{{ tower_password }}"
    poolboy:
      NAMESPACE: "{{ poolboy_namespace }}"
      IMAGE: quay.io/gpte-devops-automation/poolboy:{{ poolboy_version }}
    poolboy_crds:
      NAMESPACE: "{{ poolboy_namespace }}"

secrets: '{{
  {
    agnosticv_operator_namespace: {
      "agnosticv-operator-sshkey": {
        "id_rsa": agnosticv_repo_ssh_key
      }
    },
    anarchy_operator_namespace: {
      "innolabs": {
        "aws_access_key_id": aws_access_key_id,
        "aws_secret_access_key": aws_secret_access_key
      }
    }
  }
}}'

openshift_cluster_content:
  - object: Create projects
    content:
      - name: Create Poolboy namespace
        template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
        action: create
        params_from_vars:
          NAMESPACE: "{{ poolboy_namespace }}"
          NAMESPACE_DISPLAY_NAME: "{{ poolboy_namespace }}"
        tags:
          - poolboy
          - poolboy-namespace
      - name: Create Anarchy Operator namespace
        template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
        action: create
        params_from_vars:
          NAMESPACE: "{{ anarchy_operator_namespace }}"
          NAMESPACE_DISPLAY_NAME: "{{ anarchy_operator_namespace }}"
        tags:
          - anarchy
          - anarchy-namespace
      - name: Create Agnosticv Operator namespace
        template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/v3.9.0/files/projectrequest/template.yml"
        action: create
        params_from_vars:
          NAMESPACE: "{{ agnosticv_operator_namespace }}"
          NAMESPACE_DISPLAY_NAME: "{{ agnosticv_operator_namespace }}"
        tags:
          - agnosticv
          - agnosticv-namespace
  - object: Deploy operators
    content:
      - name: Deploy Poolboy
        namespace: "{{ poolboy_namespace }}"
        template: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/poolboy/{{ poolboy_version }}/deploy-template.yaml
        params_from_vars: "{{ operators.deploy.poolboy }}"
        tags:
          - poolboy
          - poolboy-operator
      - name: Deploy Poolboy CRDs
        namespace: "{{ poolboy_namespace }}"
        template: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/poolboy/{{ poolboy_version }}/integration/anarchy-operator/deploy-template.yaml
        params_from_vars: "{{ operators.deploy.poolboy_crds }}"
        tags:
          - poolboy
          - poolboy-crds
          - poolboy-operator
      - name: Deploy Anarchy Operator
        namespace: "{{ anarchy_operator_namespace }}"
        template: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/anarchy-operator/{{ anarchy_version }}/deploy-template.yaml
        params_from_vars: "{{ operators.deploy.anarchy }}"
        tags:
          - anarchy
          - anarchy-operator
      - name: Deploy Agnosticv Operator
        namespace: "{{ agnosticv_operator_namespace }}"
        # Need to use master because there are no tags/releases for agnostiv-operator
        #template: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/agnosticv-operator/{{ agnosticv_version }}/deploy-template.yaml
        template: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/agnosticv-operator/master/deploy-template.yaml
        params_from_vars: "{{ operators.deploy.agnosticv }}"
        tags:
          - agnosticv
          - agnosticv-operator
  - object: Create secrets
    content:
      - name: Create secrets
        file: "{{ inventory_dir }}/../.openshift/templates/secrets.j2"
        tags:
          - agnosticv
          - anarchy
          - poolboy
          - secrets
  - object: Deploy AnarchyAPI CR
    content:
      - name: Deploy AnarchyAPI CR
        template: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/anarchy-operator/{{ anarchy_version }}/integration/babylon/deploy-template.yaml
        params_from_vars: "{{ operators.deploy.anarchy_api }}"
        tags:
          - anarchy-api
  - object: Deploy ResourceProvider CR
    content:
      - name: Deploy ResourceProvicer CR
        file: https://raw.githubusercontent.com/redhat-gpte-devopsautomation/poolboy/{{ poolboy_version }}/integration/anarchy-operator/babylon-provider.yaml
        tags:
          - poolboy-resource-provider
...
