---
apiVersion: poolboy.gpte.redhat.com/v1
kind: ResourceProvider
metadata:
  name: babylon
  namespace: {{ .Values.poolboy.namespace }}
spec:
  default:
    spec:
      vars:
        desired_state: started
  match:
    apiVersion: {{ .Values.anarchy.apiGroup }}/v1
    kind: AnarchySubject
    metadata:
      annotations:
        poolboy.gpte.redhat.com/resource-provider-name: babylon
  matchIgnore:
  # Allow match to subjects that are currently stopped or provisioning.
  - /spec/vars/current_state
  - /spec/vars/desired_state
  # Ignore cloud tags when subject is requested. If matched to an existing
  # subject then cloud tags will not be applied unless update functionality
  # is implemented.
  - /spec/vars/job_vars/cloud_tags(/.*)?
  # Ignore match for dynamic fields set on service request
  - /spec/vars/job_vars/email
  - /spec/vars/job_vars/ipa_host_password
  - /spec/vars/job_vars/serviceid
  - /spec/vars/job_vars/student_name
  override:
    metadata:
      namespace: {{ .Values.anarchy.namespace }}
    spec:
      vars:
        babylon_user_email: >-
          {{ "{{: requester_identity.extra.email | default(None) if requester_identity else None :}}" }}
        babylon_user_fullname: >-
          {{ "{{: requester_identity.extra.name | default(None) if requester_identity else None :}}" }}
        babylon_username: >-
          {{ "{{: requester_user.metadata.name | default(None) if requester_user else None :}}" }}
        job_vars:
          guid: >-
            {{ "{{: resource_handle.metadata.name[5:] if resource_handle.metadata.name.startswith('guid-') else resource_handle.metadata.name :}}" }}
          uuid: >-
            {{ "{{: resource_handle.metadata.uid :}}" }}
  updateFilters:
  - pathMatch: /spec/vars/desired_state
  validation:
    openAPIV3Schema:
      type: object
      additionalProperties: false
      required:
      - apiVersion
      - kind
      - metadata
      - spec
      properties:
        apiVersion:
          type: string
          enum:
          - {{ .Values.anarchy.apiGroup }}/v1
        kind:
          type: string
          enum:
          - AnarchySubject
        metadata:
          type: object
          additionalProperties: false
          properties:
            annotations:
              additionalProperties:
                type: string
              type: object
            generateName:
              type: string
            labels:
              additionalProperties:
                type: string
              type: object
        spec:
          type: object
          required:
          - governor
          additionalProperties: false
          properties:
            governor:
              type: string
            vars:
              type: object
              properties:
                desired_state:
                  enum:
                  - started
                  - stopped
                  type: string
